name: android

on: workflow_dispatch


jobs:
  build_android:

    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ndk

    
    strategy:
      matrix:
          config:
            - {
                compiler: aarch64-linux-android21-clang++,
                arch: armv8
              }
            - {
                compiler: armv7a-linux-androideabi21-clang++,
                arch: armv7-neon
              }
            - {
                compiler: armv7a-linux-androideabi21-clang++,
                arch: armv7 
              }


    name: build_android
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ianfab/Fairy-Stockfish
          ref: fairy_sf_14_0_1_xq

      - name: Download required linux packages
        run: |
          sudo apt update
          sudo apt install expect valgrind g++-multilib qemu-user


      - name: Check compiler
        run: |
          export PATH=$PATH:$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          ls $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin
          $COMPILER -v
      
      - name: Test help target
        run: |
          make help

      - name: Test build
        run: |
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          SDKMANAGER=${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager
          echo "y" | $SDKMANAGER "ndk;25.1.8937393"
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          ln -sfn $ANDROID_SDK_ROOT/ndk/25.1.8937393 $ANDROID_NDK_ROOT
          export PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$PATH
          export LDFLAGS="-static -Wno-unused-command-line-argument"
          make clean
          make -j2 ARCH=${{ matrix.config.arch }} build

      - name: Show File
        run: file stockfish

      - uses: actions/upload-artifact@v3.1.0
        with:
          name: Fairy-Stockfish-${{ matrix.config.arch }}
          path: ./src/stockfish
